### ISSUE TITLE
How to bind class like LuaBridge?

### ISSUE THREAD

**Issue by leaker** [AdUki/LuaState#15] opened 2014-10-25 18:49 UTC
In LuaBridge, can register class like this:

``` c++
struct A {
  static int staticData;
  static float staticProperty;

  static float getStaticProperty () { return staticProperty; }
  static void setStaticProperty (float f) { staticProperty = f; }
  static void staticFunc () { }

  static int staticCFunc () { return 0; }

  std::string dataMember;

  char dataProperty;
  char getProperty () const { return dataProperty; }
  void setProperty (char v) { dataProperty = v; }

  void func1 () { }
  virtual void virtualFunc () { }

  int cfunc (lua_State* L) { return 0; }
};

struct B : public A {
  double dataMember2;

  void func1 () { }
  void func2 () { }
  void virtualFunc () { }
};

int A::staticData;
float A::staticProperty;
```

are registered using:

``` c++
getGlobalNamespace (L)
  .beginNamespace ("test")
    .beginClass <A> ("A")
      .addConstructor <void (*) (void)> ()
      .addStaticData ("staticData", &A::staticData)
      .addStaticProperty ("staticProperty", &A::staticProperty)
      .addStaticFunction ("staticFunc", &A::staticFunc)
      .addStaticCFunction ("staticCFunc", &A::staticCFunc)
      .addData ("data", &A::dataMember)
      .addProperty ("prop", &A::getProperty, &A::setProperty)
      .addFunction ("func1", &A::func1)
      .addFunction ("virtualFunc", &A::virtualFunc)
      .addCFunction ("cfunc", &A::cfunc)
    .endClass ()
    .deriveClass <B, A> ("B")
      .addConstructor <void (*) (void)> ()
      .addData ("data", &B::dataMember2)
      .addFunction ("func1", &B::func1)
      .addFunction ("func2", &B::func2)
    .endClass ()
  .endNameSpace ();
```

Use in lua:

``` lua
local obj_a = A() -- create object obj_a from new A
```

How to in LuaState?

**Comment by AdUki** [comment] 2014-10-26 00:03
You can't bind whole classes in LuaState. But you can still use LuaBridge with LuaState if you want to use this feature with no problem...

**Comment by leaker** [comment] 2014-10-26 14:51
Thx AdUki. and I like C++11 style code. it's looks cool. :)

**Comment by AdUki** [comment] 2014-10-30 22:20
Also it is kind of duplicate of #5

**Closed as completed by AdUki** 2014-10-30 22:20 UTC
Labels: duplicate, enhancement
